typography_spectrum: 0.01135086896829307
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5762655811849982
  lightness: 0.03272832278162241
  saturation: 0.007172891171649098
  rhythmicContrast: 0.3135220850817859
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6001097210682929
analytics:
  google: null
  facebook: null
  twitter: null
name: harvs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Harvs
description: Sleepless in San Antonio
purpose: []
