typography_spectrum: 0.6207591444253922
color:
  brandColors:
    - '#E6E2AF'
    - '#A7A37E'
    - '#EFECCA'
    - '#046380'
    - '#002F2F'
  brandStrength: 0.4440884036011994
  lightness: 0.8707704946864396
  saturation: 0.8899282962083817
  rhythmicContrast: 0.5529670098330826
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.6409075637347996
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Johnny Harvey
  email: johnnyharvey@gmail.com
name: Harvs
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Harvs
description: Sleepless in San Antonio
purpose: []
